### ISSUE TITLE
pull_sensor: flag impossible values (nice-to-have)

### ISSUE THREAD

**Issue by ashleyasmus** [Metropolitan-Council/tc.sensors#4]
Impossible values :

where total hourly volumes exceed 2300 -- 
or where total 30-second volumes exceed 20 cars

or

where total hourly occupancy exceeds 216,000 (the number of scans per hour)
or where total 30-second occupancy values exceed 1800 (I think?? Is that right? ) 

I do this later down the road but would be nice to have pull_sensor either null the impossible values, or put up a new field to flag them. 

```
   # GET RID OF IMPOSSIBLE VALUES ----
    hourlydat_sensor <- hourlydat_sensor[,volume.sum:=ifelse(volume.sum>=2300, NA, volume.sum)]
    # 60 scans per second * 60 secs per min * 60 mins per hour = 216,000 scans per hour
    hourlydat_sensor <- hourlydat_sensor[,occupancy.sum:=ifelse(occupancy.sum>=216000, NA, occupancy.sum)]

```

**Comment by eroten** [comment]
This issue is closed via `replace_impossible()`. which replaces impossible values with `NA` for 30 second data and aggregated data at any level 24 hours or less (10 minutes, 15 minutes, 1 hour...).

bf320d3f28beded32cd92da9a83ce5d9cd9667dd
