### ISSUE TITLE
pull_sensor: allow user to specify time interval

### ISSUE THREAD

**Issue by ashleyasmus** [Metropolitan-Council/tc.sensors#5]
At the moment pull_sensor gets data at 30-second intervals, then writes it to a file, then you can do stuff with the new data. But nobody wants 30-second data. Would be nice if you could specify one of a few common intervals (15-minute, hourly, daily).

**Comment by ashleyasmus** [comment]
this might be obsolete if we start just pulling the data into a database. so i wouldn't prioritize it.

**Comment by eroten** [comment]
How do you aggregate to hourly data right now?

**Comment by eroten** [comment]
@ashleyasmus , check out `aggregate_sensor_data()` when you get the chance!

**Comment by eroten** [comment]
Aggregating up to any time interval from the raw, 30 sec. records takes place in `aggregate_sensor()` and was released in #12
