### ISSUE TITLE
pull_sensor: use data_table wherever possible

### ISSUE THREAD

**Issue by ashleyasmus** [Metropolitan-Council/tc.sensors#6]
Noticed that replacing base r functions with data_table functions can speed up operations. Not sure how many base r commands are lingering in the original code but it'd be worth keeping an eye out!

**Comment by eroten** [comment]
Ah, yes. I'm way more comfortable with tidyverse, but I could use [`{dtplyr}`](https://github.com/tidyverse/dtplyr) to translate

**Comment by eroten** [comment]
I am closing this issue and making a note in #9 about using `{data.tabe}` instead of `{dplyr}` and friends.
