### ISSUE TITLE
Calculate speed function + vignette

### ISSUE THREAD

**Issue by eroten** [Metropolitan-Council/tc.sensors#7]
Write function and vignette for calculating speed from `pull_sensor()` return

**Comment by ashleyasmus** [comment]
For hourly speed data I do: 

```
  # CALCULATE SPEED --- 
    hourlydat_sensor[,occupancy.pct := (occupancy.sum/216000)]
    hourlydat_sensor[,speed:=ifelse(volume.sum != 0, 
                                    (volume.sum*detector_field)/(5280*occupancy.pct), 0)]
```

**Comment by eroten** [comment]
What intervals do you think are needed? Hourly, time periods (morning rush, evening rush), daily?

**Comment by eroten** [comment]
Speed was integrated into `aggregate_sensor()` in PR #12
